### ISSUE TITLE
Updating this image for mStream v5

### ISSUE THREAD

**Issue by IrosTheBeggar** [linuxserver/docker-mstream#10]
Hi, I'm working on releasing v5 of mStream. This update comes with some breaking changes and this Docker image will be updated.  

The biggest change that will affect this repo is that the boot process has been changed.  For v5 you must have a config file or mStream will not work. In previous versions of mStream you could boot it with just CLI flags.  This CLI flag feature has been removed.  Now the only argument you can pass to mStream is the location of the config file you want to use.  The reason for this is that I added a new Admin API + UI that handles config file modifications. 

[I tagged a v5 pre-release here](https://github.com/IrosTheBeggar/mStream/releases/tag/v5.0.0). It's stable and can be used for testing. Let me know if I can help with anything

**Comment by aptalca** [comment]
Thanks so much for the heads up. We'll get a PR ready shortly

**Comment by aptalca** [comment]
@IrosTheBeggar 
trying out the new 5.0.0 build and having issues getting the web ui working

Tried this config.json:
```
{
  "port": 3000,
  "webAppDirectory": "public",
  "writeLogs": false,
  "noUpload": true,
  "scanOptions": {
    "skipImg": false,
    "scanInterval": 1.5,
    "pause": 50,
    "saveInterval": 500,
    "bootScanDelay": 15
  },
  "storage": {
    "albumArtDirectory": "/config/album-art",
    "dbDirectory": "/config/db"
  },
  "folders": {
    "library": { "root": "/music" }
  }
}
```
mStream starts with no errors, but trying to access the gui results in `Cannot GET /` printed in the browser.

Here's the app log:
```
[services.d] starting services
[services.d] done.

             ____  _
   _ __ ___ / ___|| |_ _ __ ___  __ _ _ __ ___
  | '_ ` _ \\___ \| __| '__/ _ \/ _` | '_ ` _ \
  | | | | | |___) | |_| | |  __/ (_| | | | | | |
  |_| |_| |_|____/ \__|_|  \___|\__,_|_| |_| |_|

v5.0-beta

Breaking Changes
-- Config files from v4 will not work
-- The Android App does not work with v5 (for now)
-- You can no longer boot mStream with CLI flags

Check out our Discord server:
https://discord.gg/AM896Rr

2021-03-22T17:52:07.509Z info: Config file does not have secret.  Generating a secret and saving
2021-03-22T17:52:07.546Z info: Access mStream locally: http://0.0.0.0:3000
2021-03-22T17:52:07.560Z info: File scan started on /music
2021-03-22T17:52:07.974Z info: File scan message: finished scan

2021-03-22T17:52:07.983Z info: File scan completed with code 0
```

Any ideas?

**Comment by IrosTheBeggar** [comment]
I changed the webapp folder from `public` to `webapp`. Updating the `webAppDirectory` should fix that

**Comment by aptalca** [comment]
Yup, that was it. Thanks.

Now I gotta figure out a way to properly handle existing config.json that is not compatible with v5

**Comment by aptalca** [comment]
@IrosTheBeggar please ping us when you release v5 and we'll merge this PR: #11 

Thanks

**Comment by IrosTheBeggar** [comment]
@aptalca 

I know it's been a while. But I'm finally releasing v5. Will have it out later today. Let me know if you need more time

**Comment by aptalca** [comment]
@IrosTheBeggar sounds good. We're ready to go

**Comment by IrosTheBeggar** [comment]
@aptalca 

It's live: https://github.com/IrosTheBeggar/mStream/releases/tag/v5.1.0
