### ISSUE TITLE
[BUG] Pull failure due to high UID and GID requirements in unprivileged LXC container

### ISSUE THREAD

**Issue by Jdogzz** [linuxserver/docker-mstream#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pull fails with this error:

```
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/opt/mstream/node_modules/buffer-equal-constant-time/.npmignore" for UID 718322462, GID 454177323 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /opt/mstream/node_modules/buffer-equal-constant-time/.npmignore: invalid argument
```

It appears, from looking at these two issues:

https://github.com/moby/moby/issues/43576

https://github.com/Ylianst/MeshCentral/issues/4828

that the reason for the failure is one of the layers being pulled in has the high UID and GID values and docker is doing this in an unprivileged LXC container.

### Expected Behavior

Pull succeeds.

### Steps To Reproduce

1. Spin up unprivileged LXC on Proxmox with Turnkey Linux.
2. Use docker compose snippet from readme.
3. Pull container.

### Environment

```markdown
- OS: TurnKey GNU/Linux 17.1
- How docker service was installed:
Using option 1 here with bash script for grabbing docker: https://docs.linuxserver.io/general/docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  mstream:
    image: lscr.io/linuxserver/mstream:latest
    container_name: mstream
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mylocation1:/config
      - /mylocation2:/music
    ports:
      - 3000:3000
    restart: unless-stopped
```

### Container logs

```bash
Error response from daemon: No such container: linuxserver.io
```

**Comment by thespad** [comment]
I can't replicate your issue even with unpriv LXC (which FWIW we don't support or test against), it pulls and runs fine for me. I don't know how Proxmox configures its LXC implementation but it seems to be a persistent source of issues for people.

You can try `lspipepr/mstream:v5.11.4-pkg-b56a318e-pr-19` and see if it resolves the issue for you, but beyond that I don't have any ideas beyond you expanding your subuid/subgid pools.

**Comment by Jdogzz** [comment]
@thespad Thanks for the very quick reply and the fix! I tested the new build and it successfully pulled the build and is running smoothly now with some minimal testing.
