### ISSUE TITLE
Sorry for commenting here, but I have a question, how can I disable the song download option in mstream i'm using mstream v4.7.0?

### ISSUE THREAD

**Issue by jpurca** [linuxserver/docker-mstream#6]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Command used to create docker container (run/create/compose/screenshot)
docker create \
  --name=mstreamtest \
  -e PUID=1000 \
  -e PGID=1000 \
  -e USER=***** \
  -e PASSWORD=******* \
  -e USE_JSON=false \
  -e TZ=America/Bogota \
  -p 3000:3000 \
  -v /Users/jp/Desktop/music/configtest:/config \
  -v /Users/jp/Desktop/music:/music \
  --restart unless-stopped \
  linuxserver/mstream

## Docker logs
User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-certs: executing... 
[cont-init.d] 20-certs: exited 1.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

  v4.7.0     ____  _
   _ __ ___ / ___|| |_ _ __ ___  __ _ _ __ ___
  | '_ ` _ \\___ \| __| '__/ _ \/ _` | '_ ` _ \
  | | | | | |___) | |_| | |  __/ (_| | | | | | |
  |_| |_| |_|____/ \__|_|  \___|\__,_|_| |_| |_|
  Paul Sori - paul@mstream.io

Find a bug? Report it at:
https://github.com/IrosTheBeggar/mStream/issues

2020-04-26T16:00:33.569Z info: Access mStream locally: http://localhost:3000
2020-04-26T16:00:33.570Z info: Try the WinAmp Demo: http://localhost:3000/winamp
2020-04-26T16:00:36.577Z info: File scan started on /music
2020-04-26T16:01:49.296Z info: File scan message: database saved
2020-04-26T16:02:42.908Z info: File scan message: database saved
2020-04-26T16:02:42.940Z info: File scan completed with code 0

**Comment by j0nnymoe** [comment]
This question is better suited for mStream directly.
